// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ProductSkusStatus string

const (
	ProductSkusStatusActive   ProductSkusStatus = "active"
	ProductSkusStatusInactive ProductSkusStatus = "inactive"
)

func (e *ProductSkusStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductSkusStatus(s)
	case string:
		*e = ProductSkusStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductSkusStatus: %T", src)
	}
	return nil
}

type NullProductSkusStatus struct {
	ProductSkusStatus ProductSkusStatus `json:"product_skus_status"`
	Valid             bool              `json:"valid"` // Valid is true if ProductSkusStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductSkusStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductSkusStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductSkusStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductSkusStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductSkusStatus), nil
}

type ProductStatus string

const (
	ProductStatusDraft    ProductStatus = "draft"
	ProductStatusActive   ProductStatus = "active"
	ProductStatusArchived ProductStatus = "archived"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"product_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type Product struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      ProductStatus      `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProductSku struct {
	ID         uuid.UUID          `json:"id"`
	ProductID  uuid.UUID          `json:"product_id"`
	Code       string             `json:"code"`
	PriceCents int64              `json:"price_cents"`
	Currency   string             `json:"currency"`
	Status     ProductSkusStatus  `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
