// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products
    (name, description)
VALUES ($1, $2)
    RETURNING id
`

type CreateProductParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Description)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createProductSKU = `-- name: CreateProductSKU :one
INSERT INTO product_skus
    (product_id, code, price_cents, currency)
VALUES
    ($1, $2, $3, $4)
    RETURNING id
`

type CreateProductSKUParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	Code       string    `json:"code"`
	PriceCents int64     `json:"price_cents"`
	Currency   string    `json:"currency"`
}

func (q *Queries) CreateProductSKU(ctx context.Context, arg CreateProductSKUParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProductSKU,
		arg.ProductID,
		arg.Code,
		arg.PriceCents,
		arg.Currency,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    p.id as product_id,
    ps.id as product_sku_id,
    p.name,
    p.description,
    ps.code,
    ps.price_cents,
    ps.currency
FROM
    products p
INNER JOIN
    product_skus ps
ON
    p.id = ps.product_id
WHERE
    p.id = $1
`

type GetProductByIDRow struct {
	ProductID    uuid.UUID `json:"product_id"`
	ProductSkuID uuid.UUID `json:"product_sku_id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	Code         string    `json:"code"`
	PriceCents   int64     `json:"price_cents"`
	Currency     string    `json:"currency"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ProductID,
		&i.ProductSkuID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.PriceCents,
		&i.Currency,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
    p.id as product_id,
    ps.id as product_sku_id,
    p.name,
    p.description,
    ps.code,
    ps.price_cents,
    ps.currency
FROM
    products p
INNER JOIN
    product_skus ps
ON
    p.id = ps.product_id
ORDER BY
    p.created_at DESC, p.id DESC
LIMIT $1
OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsRow struct {
	ProductID    uuid.UUID `json:"product_id"`
	ProductSkuID uuid.UUID `json:"product_sku_id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	Code         string    `json:"code"`
	PriceCents   int64     `json:"price_cents"`
	Currency     string    `json:"currency"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductSkuID,
			&i.Name,
			&i.Description,
			&i.Code,
			&i.PriceCents,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
